### ISSUE TITLE
Superscripts aren't all Superscripts?

### ISSUE THREAD

**Issue by arnicas** [learntextvis/word-cloud#8]
Not sure whether this was an intentional design decision, but i'd prefer if the superscripts were always super. Top row has them in the middle? 

![image](https://cloud.githubusercontent.com/assets/377341/12490755/2bb3a11a-c045-11e5-9bec-e95c74fb9382.png)

**Comment by tafsiri** [comment]
they are all <sup> tags, with default display, i wonder if they need some extra css since there are different sized words in a given line?

**Comment by tafsiri** [comment]
lol at that formatting

**Comment by arnicas** [comment]
I assumed you did that on purpose!! :)
